# Generated by Django 5.1.3 on 2025-01-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portabilityoutbox',
            name='activities',
        ),
        migrations.CreateModel(
            name='CreateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers-only', 'Followers only')], default='public', max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='core.actor')),
                ('note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_activities', to='core.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portabilityoutbox',
            name='activities_create',
            field=models.ManyToManyField(related_name='outboxes', to='core.createactivity'),
        ),
        migrations.CreateModel(
            name='FollowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers-only', 'Followers only')], default='public', max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='core.actor')),
                ('target_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_activities_received', to='core.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portabilityoutbox',
            name='activities_follow',
            field=models.ManyToManyField(related_name='outboxes', to='core.followactivity'),
        ),
        migrations.CreateModel(
            name='LikeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers-only', 'Followers only')], default='public', max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_activities', to='core.actor')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_activities', to='core.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portabilityoutbox',
            name='activities_like',
            field=models.ManyToManyField(related_name='outboxes', to='core.likeactivity'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
