# Generated by Django 5.1.3 on 2025-03-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likeactivity_object_data_likeactivity_object_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followactivity',
            name='target_actor_data',
            field=models.JSONField(blank=True, help_text='Metadata of the followed actor', null=True),
        ),
        migrations.AddField(
            model_name='followactivity',
            name='target_actor_url',
            field=models.URLField(blank=True, help_text='URL of the followed actor in the fediverse', null=True),
        ),
        migrations.AlterField(
            model_name='followactivity',
            name='target_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_activities_received', to='core.actor'),
        ),
    ]
