# Generated by Django 5.1.3 on 2025-06-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_convert_oauthconnections_to_applications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthConnection',
        ),
    ]
