# Generated by Django 5.1.3 on 2025-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followactivity_target_actor_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='previously',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
