# Generated by Django 5.1.3 on 2025-08-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_oauthconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_actor_url', models.URLField(blank=True, help_text='ActivityPub Actor URL for remote followers', max_length=500, null=True)),
                ('follower_actor_data', models.JSONField(blank=True, help_text='Cached metadata of the remote follower actor', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='core.actor')),
                ('follower_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_others_relationships', to='core.actor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('follower_actor__isnull', False)), fields=('actor', 'follower_actor'), name='unique_local_follower'), models.UniqueConstraint(condition=models.Q(('follower_actor_url__isnull', False)), fields=('actor', 'follower_actor_url'), name='unique_remote_follower')],
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_actor_url', models.URLField(blank=True, help_text='ActivityPub Actor URL for remote follows', max_length=500, null=True)),
                ('target_actor_data', models.JSONField(blank=True, help_text='Cached metadata of the followed remote actor', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='core.actor')),
                ('target_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_relationships', to='core.actor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_actor__isnull', False)), fields=('actor', 'target_actor'), name='unique_local_following'), models.UniqueConstraint(condition=models.Q(('target_actor_url__isnull', False)), fields=('actor', 'target_actor_url'), name='unique_remote_following')],
            },
        ),
    ]
