# Generated by Django 5.1.3 on 2025-09-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_oauth_client_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_actor_url', models.URLField(blank=True, help_text='ActivityPub Actor URL for remote blocks', max_length=500, null=True)),
                ('blocked_actor_data', models.JSONField(blank=True, help_text='Cached metadata of the blocked remote actor', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason for blocking (for user reference, not shared)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_relationships', to='core.actor')),
                ('blocked_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relationships', to='core.actor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('blocked_actor__isnull', False)), fields=('actor', 'blocked_actor'), name='unique_local_blocked'), models.UniqueConstraint(condition=models.Q(('blocked_actor_url__isnull', False)), fields=('actor', 'blocked_actor_url'), name='unique_remote_blocked')],
            },
        ),
    ]
