# Generated by Django 5.1.3 on 2026-04-22 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blocked'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActorBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The source Actor this token is authorized to access.', on_delete=django.db.models.deletion.CASCADE, related_name='portability_token_bindings', to='core.actor')),
                ('token', models.OneToOneField(help_text='The OAuth access token this binding belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='actor_binding', to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
        ),
    ]
