# Generated by Django 5.1.3 on 2026-09-08 21:48

import django.db.models.deletion
import testbed.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_token_actor_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_base_url', models.URLField(help_text='Base URL of the source server. Everything else about the source is discovered from it.', max_length=500)),
                ('source_actor_url', models.URLField(blank=True, help_text='Source Actor URL as supplied or resolved by discovery. Advisory, not authoritative.', max_length=500, null=True)),
                ('authorized_actor_url', models.URLField(blank=True, help_text='The Actor URL the source returned in `activitypub_actor` on the callback (LOLA §5.3).', max_length=500, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('failed', 'Failed')], default='active', help_text='The working phase is derived from the data, not stored.', max_length=16)),
                ('retry_when', models.DateTimeField(blank=True, help_text="Set from a 429's Retry-After. A job is paused.", null=True)),
                ('policy', models.JSONField(blank=True, default=testbed.core.models.default_transfer_policy, help_text='Chosen when the job is created. Changing the decision means a new job rather than an edit.')),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Per-collection resume state. Read and written only.')),
                ('artifacts', models.JSONField(blank=True, default=dict, help_text='References to captured raw payloads, never the payload bodies.')),
                ('error', models.TextField(blank=True, default='', help_text='The single terminal reason this job failed: source unreachable, authorization revoked, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_actor', models.ForeignKey(help_text='The destination Actor imported content is written to.', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='core.actor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('content', 'Content'), ('outbox', 'Outbox'), ('following', 'Following'), ('blocked', 'Blocked'), ('liked', 'Liked')], help_text='Which LOLA collection this object was fetched from.', max_length=32)),
                ('source_id', models.URLField(help_text="The object's ID on the source server. Also the duplicate-detection key.", max_length=500)),
                ('destination_id', models.URLField(blank=True, help_text='The new ID created for the copy. Null for dry-run (writes no objects), and for skipped or failed items.', max_length=500, null=True)),
                ('object_type', models.CharField(blank=True, default='', help_text='The type as received: Note, Create, Like, Follow, Block.', max_length=64)),
                ('outcome', models.CharField(choices=[('imported', 'Imported'), ('skipped', 'Skipped'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], help_text='What happened to this object. No default: a row is written at its outcome.', max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Why this outcome: the skip reason, the validation error, the earlier job that already imported it, or a flag that an unmappable visibility was defaulted to private.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='The run this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transferjob')),
            ],
            options={
                'ordering': ['job', 'collection', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transferjob',
            index=models.Index(fields=['destination_actor', 'state'], name='transferjob_actor_state_idx'),
        ),
        migrations.AddIndex(
            model_name='transferjob',
            index=models.Index(fields=['state', 'retry_when'], name='transferjob_state_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferjob',
            constraint=models.CheckConstraint(condition=models.Q(('error', ''), ('state', 'failed'), _negated=True), name='transferjob_failed_has_reason'),
        ),
        migrations.AddIndex(
            model_name='transferreditem',
            index=models.Index(fields=['job', 'collection'], name='transferitem_job_coll_idx'),
        ),
        migrations.AddIndex(
            model_name='transferreditem',
            index=models.Index(fields=['source_id'], name='transferitem_source_id_idx'),
        ),
    ]
