# Generated by Django 5.1.3 on 2026-09-02 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transfer_job_and_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cc',
            field=models.JSONField(blank=True, default=list, help_text='Same rule as `to`: descriptive, never an access decision.'),
        ),
        migrations.AddField(
            model_name='note',
            name='in_reply_to',
            field=models.URLField(blank=True, help_text='The object this one replies to. LOLA §7.1.5.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='previously',
            field=models.JSONField(blank=True, default=list, help_text='Object breadcrumbs: [{actor, id}], newest first (LOLA §7.1.8).'),
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.JSONField(blank=True, help_text='Original markup as authored. LOLA §6.3.', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Short human-readable summary précis of the object. LOLA §6.3.'),
        ),
        migrations.AddField(
            model_name='note',
            name='to',
            field=models.JSONField(blank=True, default=list, help_text='Descriptive only: a historical record of where the object was distributed. LOLA §7.1.6.'),
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True, help_text='Canonical human-facing URL of the object at its origin. LOLA §6.3.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='published',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the object was originally published.'),
        ),
    ]
