# Generated by Django 5.1.3 on 2026-09-03 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_note_settable_published_and_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='createactivity',
            name='previously',
            field=models.JSONField(blank=True, default=list, help_text='Activity breadcrumbs: [{actor, id}], newest first (LOLA §7.1.8).'),
        ),
        migrations.AddField(
            model_name='followactivity',
            name='previously',
            field=models.JSONField(blank=True, default=list, help_text='Activity breadcrumbs: [{actor, id}], newest first (LOLA §7.1.8).'),
        ),
        migrations.AddField(
            model_name='likeactivity',
            name='previously',
            field=models.JSONField(blank=True, default=list, help_text='Activity breadcrumbs: [{actor, id}], newest first (LOLA §7.1.8).'),
        ),
        migrations.AlterField(
            model_name='createactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity originally happened.'),
        ),
        migrations.AlterField(
            model_name='followactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity originally happened.'),
        ),
        migrations.AlterField(
            model_name='likeactivity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity originally happened.'),
        ),
    ]
