"""
Django settings for testbed project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import logging
import environ
import structlog
from google.cloud.logging import Client as CloudLoggingClient
from google.cloud.logging.handlers import CloudLoggingHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

PROJECT_NAME = "ActivityPub-Testbed"
SITE_URL = "[localhost]"

# SECURITY WARNING: keep the secret key used in production secret
SECRET_KEY = env.str("DJANGO_SECRET_KEY", default="django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = True

ALLOWED_HOSTS = []

# Allow seeding in development by default (will be overridden in production/staging)
ALLOWED_SEED_COMMAND = True

logger = logging.getLogger(__name__)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "testbed.core",
    "rest_framework",
    "sass_processor",
    "allauth",
    "allauth.account",
    "oauth2_provider",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # LOLA Rate Limiting - positioned early to protect all endpoints
    "testbed.core.middleware.rate_limiting.BasicRateLimitingMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "allauth.account.middleware.AccountMiddleware"
]

ROOT_URLCONF = "testbed.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "testbed.wsgi.application"

# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Force SQLite for base/development (will be overridden in production/staging)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
STATIC_ROOT = env.str("DJANGO_STATIC_ROOT", str(BASE_DIR.joinpath("staticfiles")))

# SASS
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder'
]
SASS_PROCESSOR_AUTO_INCLUDE = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Structlog setup
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.TimeStamper(fmt="%H:%M:%S"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
),

# Feature flag for Cloud Logging (enabled in staging/production via USE_GCLOUD_LOGGING=1)
USE_GCLOUD_LOGGING = os.environ.get('USE_GCLOUD_LOGGING', '0') == '1'

CLOUD_LOGGING_HANDLER = None
if USE_GCLOUD_LOGGING:
    try:
        cloud_logging_client = CloudLoggingClient()
        CLOUD_LOGGING_HANDLER = CloudLoggingHandler(
            cloud_logging_client,
            name="testbed"
        )
        from testbed.core.utils.logging_filters import CloudRunTraceFilter
        CLOUD_LOGGING_HANDLER.addFilter(CloudRunTraceFilter())
    except Exception as e:
        logger.warning(f"Warning: Failed to initialize Cloud Logging: {e}")
        USE_GCLOUD_LOGGING = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(
                pad_event=0,
            ),
        },
        "key_value": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.KeyValueRenderer(
                key_order=["timestamp", "level", "event", "logger"]
            ),
        },
        "rich": {"datefmt": "[%X]"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
        },
        "rich_console": {
            "class": "rich.logging.RichHandler",
            "formatter": "rich",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["rich_console"],
            "level": "INFO",
            "propagate": False,
        },
        "testbed": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Add Cloud Logging handler when enabled (staging/production)
if USE_GCLOUD_LOGGING and CLOUD_LOGGING_HANDLER:
    LOGGING["handlers"]["cloud_logging"] = {
        "()": lambda: CLOUD_LOGGING_HANDLER,
    }
    
    LOGGING["loggers"]["django"]["handlers"] = ["cloud_logging"]
    LOGGING["loggers"]["testbed"]["handlers"] = ["cloud_logging"]
    
    LOGGING["root"] = {
        "handlers": ["cloud_logging"],
        "level": "INFO",
    }
    
    LOGGING["loggers"]["django.request"] = {
        "handlers": ["cloud_logging"],
        "level": "INFO",
        "propagate": False,
    }
    LOGGING["loggers"]["gunicorn"] = {
        "handlers": ["cloud_logging"],
        "level": "INFO",
        "propagate": False,
    }
    LOGGING["loggers"]["gunicorn.error"] = {
        "handlers": ["cloud_logging"],
        "level": "INFO",
        "propagate": False,
    }
    LOGGING["loggers"]["gunicorn.access"] = {
        "handlers": ["cloud_logging"],
        "level": "INFO",
        "propagate": False,
    }

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
LOGIN_REDIRECT_URL = '/'

ACCOUNT_ADAPTER = 'testbed.core.adapters.TestbedAccountAdapter'

# Authentication URLs
LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Email configuration - default to console backend for development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@dt-reg.org'

# OAuth2 provider configuration
OAUTH2_PROVIDER = {
    'SCOPES': {
        'activitypub_account_portability': 'ActivityPub Account Portability',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # 1 hour
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400,  # 1 day
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,  # 10 minutes
    'OAUTH2_VALIDATOR_CLASS': 'testbed.core.utils.oauth_validators.ActivityPubOAuth2Validator',
    # For testing purposes -> make PKCE optional
    'PKCE_REQUIRED': False,
}

# Configure REST framework to use OAuth2 authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}
