name: CI-CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-and-seed:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testbed_ap_user
          POSTGRES_PASSWORD: testbed_dti
          POSTGRES_DB: testbed_ap
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      PROJECT_NAME: ${{ fromJson(secrets.TESTBED_ACTIONS_SECRETS).PROJECT_NAME }}
      DJANGO_SECRET_KEY: ${{ fromJson(secrets.TESTBED_ACTIONS_SECRETS).DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: ${{ fromJson(secrets.TESTBED_ACTIONS_SECRETS).DJANGO_DEBUG }}
      DJANGO_ALLOWED_HOSTS: ${{ fromJson(secrets.TESTBED_ACTIONS_SECRETS).DJANGO_ALLOWED_HOSTS }}
      DJ_DATABASE_CONN_STRING: ${{ fromJson(secrets.TESTBED_ACTIONS_SECRETS).DJ_DATABASE_CONN_STRING }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and seed database
        run: |
          python manage.py migrate
          python manage.py seed --no-prompt
        
      - name: Run tests
        run: pytest